services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules
    secrets:
      - server_certificate
      - server_key


volumes:
  frontend_modules:
  backend_modules:

secrets:
  server_certificate:
    file: ./backend/secrets/cert.pem
  server_key:
    file: ./backend/secrets/key.pem